#pragma once

#define WA_BUTTON_PREV WINAMP_BUTTON1
#define WA_BUTTON_PLAY WINAMP_BUTTON2
#define WA_BUTTON_PAUSE WINAMP_BUTTON3
#define WA_BUTTON_STOP WINAMP_BUTTON4
#define WA_BUTTON_NEXT WINAMP_BUTTON5

#define WA_PLAYING   1
#define WA_SHOW_FILE_INFO_DLG   40188
#define IPC_PE_DELETEINDEX        104
