#pragma once

#define WA_BUT_PREV WINAMP_BUTTON1
#define WA_BUT_PLAY WINAMP_BUTTON2
#define WA_BUT_PAUSE WINAMP_BUTTON3
#define WA_BUT_STOP WINAMP_BUTTON4
#define WA_BUT_NEXT WINAMP_BUTTON5

#define WA_PLAYING   1
